name: shop-global

include:
  - services/auth/docker-compose.prod.yaml
  - services/notification/docker-compose.prod.yaml
  - services/catalog/docker-compose.prod.yaml

services:
  global-nginx:
    image: nginx:alpine
    container_name: global-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      auth-nginx:
        condition: service_healthy
    networks:
      - shop_global
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --no-check-certificate --tries=1 --spider https://localhost/auth/api/healthz || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: global-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - shop_global
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  rabbitmq_data:

networks:
  shop_global:
    name: shop_global
    driver: bridge
