name: shop-local

include:
  # - services/auth/docker-compose.yaml
  # - services/notification/docker-compose.yaml

services:
  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_gateway/conf.d:/etc/nginx/conf.d:ro
      - ./nginx_gateway/ssl:/etc/nginx/ssl:ro
    

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: