services:
  nginx-base:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro 